# Generated by Django 5.1.5 on 2025-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('evp_class', models.CharField(blank=True, choices=[('SV', 'Руководитель'), ('Admin', 'Администратор'), ('TL', 'TeamLeader'), ('EVP-4', 'EVP-4'), ('EVP-5', 'EVP-5'), ('EVP-6', 'EVP-6'), ('EVP-7', 'EVP-7'), ('EVP-8', 'EVP-8')], max_length=10, null=True)),
                ('workshop', models.CharField(blank=True, choices=[('PPS', 'Цех прессования'), ('BS', 'Кузовной цех'), ('PS', 'Покрасочный цех'), ('T&C', 'Отделка и шасси'), ('MH', 'Погрузочный цех')], max_length=3, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('on_leave', models.CharField(blank=True, choices=[('SVO', 'СВО'), ('DEC', 'Декрет')], max_length=3, null=True)),
            ],
        ),
    ]
