# Generated by Django 5.1.5 on 2025-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVP_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_evp_class', models.CharField(blank=True, choices=[('SV', 'Руководитель'), ('Admin', 'Администратор'), ('TL', 'TeamLeader'), ('EVP-4', 'EVP-4'), ('EVP-5', 'EVP-5'), ('EVP-6', 'EVP-6'), ('EVP-7', 'EVP-7'), ('EVP-8', 'EVP-8')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='evp_class',
        ),
        migrations.AddField(
            model_name='stuff',
            name='evp_class',
            field=models.ManyToManyField(blank=True, to='autozavod_app.evp_class'),
        ),
    ]
