# Generated by Django 5.1.5 on 2025-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0002_evp_class_remove_stuff_evp_class_stuff_evp_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evp_class',
            name='name_evp_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='evp_class',
            field=models.ManyToManyField(blank=True, null=True, to='autozavod_app.evp_class'),
        ),
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('group', models.CharField(blank=True, choices=[('ПБ', 'Пожарная безопасность'), ('ПР', 'Промышленная безопасность'), ('ОТ', 'Охрана труда'), ('ЭК', 'Экология'), ('HR', 'HR')], max_length=2, null=True)),
                ('responsible', models.ManyToManyField(blank=True, null=True, to='autozavod_app.stuff')),
            ],
        ),
    ]
