# Generated by Django 5.1.5 on 2025-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0003_alter_evp_class_name_evp_class_alter_stuff_evp_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
