# Generated by Django 5.1.5 on 2025-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0004_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='evp_class',
            field=models.ManyToManyField(blank=True, null=True, to='autozavod_app.evp_class'),
        ),
    ]
