# Generated by Django 5.1.5 on 2025-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0005_doc_evp_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
