# Generated by Django 5.1.5 on 2025-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0006_doc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='link',
            field=models.FileField(null=True, upload_to='autozavod_app/media'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='evp_class',
            field=models.ManyToManyField(blank=True, to='autozavod_app.evp_class'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='responsible',
            field=models.ManyToManyField(blank=True, to='autozavod_app.stuff'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='evp_class',
            field=models.ManyToManyField(blank=True, to='autozavod_app.evp_class'),
        ),
    ]
