# Generated by Django 5.1.5 on 2025-01-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0007_doc_link_alter_doc_evp_class_alter_doc_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_procces', models.BooleanField(blank=True, null=True)),
                ('id_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('action', models.ManyToManyField(blank=True, max_length=200, to='autozavod_app.action')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.doc')),
                ('responsible_process', models.ManyToManyField(blank=True, to='autozavod_app.stuff')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.typedoc')),
            ],
        ),
    ]
