# Generated by Django 5.1.5 on 2025-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0008_action_typedoc_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='workshop',
        ),
        migrations.AddField(
            model_name='stuff',
            name='workshop',
            field=models.ManyToManyField(blank=True, max_length=20, to='autozavod_app.workshop'),
        ),
    ]
