# Generated by Django 5.1.5 on 2025-01-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0009_workshop_remove_stuff_workshop_stuff_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='workshop',
        ),
        migrations.AddField(
            model_name='stuff',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.workshop'),
        ),
    ]
