# Generated by Django 5.1.5 on 2025-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0010_remove_stuff_workshop_stuff_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='actual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
