# Generated by Django 5.1.5 on 2025-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0011_doc_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='actual',
            field=models.CharField(blank=True, choices=[('Y', 'Актуален'), ('N', 'Не актуален')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.BooleanField(blank=True, choices=[('Y', 'Действующий'), ('N', 'Архив')], max_length=20, null=True),
        ),
    ]
