# Generated by Django 5.1.5 on 2025-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0013_alter_doc_actual_alter_doc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.workshop'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
