# Generated by Django 5.1.5 on 2025-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0014_doc_workshop_alter_stuff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='workshop',
        ),
        migrations.AddField(
            model_name='stuff',
            name='workshop',
            field=models.ManyToManyField(blank=True, null=True, to='autozavod_app.workshop'),
        ),
    ]
