# Generated by Django 5.1.5 on 2025-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0016_remove_doc_workshop_remove_stuff_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='actual',
            field=models.CharField(blank=True, choices=[('Y', 'Актуален'), ('N', 'Не актуален')], max_length=1, null=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='evp_class',
            field=models.ManyToManyField(blank=True, to='autozavod_app.evp_class', verbose_name='Группа ознакомления'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='group',
            field=models.CharField(blank=True, choices=[('ПБ', 'Пожарная безопасность'), ('ПР', 'Промышленная безопасность'), ('ОТ', 'Охрана труда'), ('ЭК', 'Экология'), ('HR', 'HR')], max_length=2, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id_doc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id документа'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='link',
            field=models.FileField(null=True, upload_to='autozavod_app/media', verbose_name='Загрузка документа'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.CharField(choices=[('Y', 'Действующий'), ('N', 'Архив')], max_length=1, verbose_name='Статус приказа'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='workshop',
            field=models.ManyToManyField(blank=True, to='autozavod_app.workshop', verbose_name='Цех'),
        ),
    ]
