# Generated by Django 5.1.5 on 2025-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0017_doc_comment_alter_doc_actual_alter_doc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='responsible_not',
            field=models.ManyToManyField(blank=True, related_name='responsible', to='autozavod_app.stuff', verbose_name='Не ознакомлены'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='responsible_not', to='autozavod_app.stuff', verbose_name='Ознакомлены'),
        ),
    ]
