# Generated by Django 5.1.5 on 2025-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0018_doc_responsible_not_alter_doc_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='order',
        ),
        migrations.AddField(
            model_name='doc',
            name='process',
            field=models.ManyToManyField(blank=True, to='autozavod_app.process', verbose_name='Действия к приказу'),
        ),
        migrations.AddField(
            model_name='doc',
            name='type_doc',
            field=models.ManyToManyField(blank=True, to='autozavod_app.typedoc', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='process',
            name='date_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_doc', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('link', models.FileField(blank=True, null=True, upload_to='autozavod_app/media', verbose_name='Загрузка документа')),
                ('evp_class', models.ManyToManyField(blank=True, to='autozavod_app.evp_class', verbose_name='Группа ознакомления')),
                ('process', models.ManyToManyField(blank=True, to='autozavod_app.process', verbose_name='Действия к распоряжению')),
                ('responsible', models.ManyToManyField(blank=True, related_name='responsible_not_orders', to='autozavod_app.stuff', verbose_name='Ознакомлены')),
                ('responsible_not', models.ManyToManyField(blank=True, related_name='responsible_orders', to='autozavod_app.stuff', verbose_name='Не ознакомлены')),
                ('workshop', models.ManyToManyField(blank=True, to='autozavod_app.workshop', verbose_name='Цех')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='orders',
            field=models.ManyToManyField(blank=True, to='autozavod_app.orders', verbose_name='Распоряжения'),
        ),
    ]
