# Generated by Django 5.1.5 on 2025-02-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0019_remove_process_order_doc_process_doc_type_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='autozavod_app/media', verbose_name='Загрузка документа'),
        ),
        migrations.AddField(
            model_name='process',
            name='name_doc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
