# Generated by Django 5.1.5 on 2025-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0020_process_comment_process_link_process_name_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Y', 'Действующий'), ('N', 'Архив')], default='Y', max_length=1, verbose_name='Статус приказа'),
        ),
    ]
