# Generated by Django 5.1.5 on 2025-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0021_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='id_doc',
        ),
        migrations.AlterField(
            model_name='doc',
            name='comment',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Y', 'Действующий'), ('N', 'Архив')], max_length=1, verbose_name='Статус приказа'),
        ),
        migrations.AlterField(
            model_name='process',
            name='comment',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
