# Generated by Django 5.1.5 on 2025-03-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0022_remove_process_id_doc_alter_doc_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='group',
            field=models.CharField(blank=True, choices=[('ПБ', 'Пожарная безопасность'), ('ПР', 'Промышленная безопасность'), ('ОТ', 'Охрана труда'), ('ЭК', 'Экология'), ('HR', 'HR')], max_length=2, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='group',
            field=models.CharField(blank=True, choices=[('ПБ', 'Пожарная безопасность'), ('ПР', 'Промышленная безопасность'), ('ОТ', 'Охрана труда'), ('ЭК', 'Экология'), ('HR', 'HR')], max_length=2, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Y', 'Действующий'), ('N', 'Архив')], default='Y', max_length=1, verbose_name='Статус приказа'),
        ),
        migrations.AlterField(
            model_name='process',
            name='action',
            field=models.ManyToManyField(blank=True, max_length=200, to='autozavod_app.action', verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='process',
            name='comment',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name_doc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='process',
            name='responsible_process',
            field=models.ManyToManyField(blank=True, to='autozavod_app.stuff', verbose_name='Ответственные'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status_procces',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.typedoc', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='evp_class',
            field=models.ManyToManyField(blank=True, to='autozavod_app.evp_class', verbose_name='Группа ознакомления'),
        ),
    ]
