# Generated by Django 5.1.5 on 2025-03-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0023_orders_group_alter_doc_group_alter_orders_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='mayor',
            field=models.ManyToManyField(blank=True, to='autozavod_app.stuff', verbose_name='Ответственные'),
        ),
        migrations.AddField(
            model_name='orders',
            name='mayor',
            field=models.ManyToManyField(blank=True, to='autozavod_app.stuff', verbose_name='Ответственные'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autozavod_app.section'),
        ),
    ]
