# Generated by Django 5.1.5 on 2025-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autozavod_app', '0024_section_doc_mayor_orders_mayor_stuff_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status_procces',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], null=True, verbose_name='Статус выполнения'),
        ),
    ]
